linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
    - godot
    - paralleltest
    - gci
    - gofumpt

linters-settings:
  errcheck:
    # report about not checking of errors in type assetions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions: true
    
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true

  gofmt:
    simplify: true
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/obalunenko/advent-of-code/
  unparam:
    algo: cha
    check-exported: false
  prealloc:
    simple: true
    range-loops: true # Report preallocation suggestions on range loops, true by default
    for-loops: false # Report preallocation suggestions on for loops, false by default
  gomnd:
    settings:
      mnd:
        # the list of enabled checks, see https://github.com/tommy-muehle/go-mnd/#checks for description.
        checks: [case,condition,operation,return]
  gocritic:
    enabled-checks:
      - docStub
      - rangeValCopy
      - yodaStyleExpr
      - appendAssign
      - appendCombine
      - caseOrder
      - badCond
      - commentedOutCode
      - commentFormatting
      - commentedOutImport
      - dupArg
      - dupBranchBody
      - elseif
      - emptyStringTest
      - indexAlloc
      - initClause
      - captlocal
      - weakCond
      - deprecatedComment
      - flagDeref
      - flagName
      - hugeParam
      - ifElseChain
      - nilValReturn
      - rangeExprCopy
      - ptrToRefParam
      - underef
      - unnecessaryBlock
      - valSwap
    settings: # settings passed to gocritic
      captLocal: # must be valid enabled check name
        paramsOnly: true
      rangeValCopy:
        sizeThreshold: 320
      hugeParam:
        sizeThreshold: 500
      rangeExprCopy:
        skipTestFuncs: true
      underef:
        skipRecvDeref: true

run:
  skip-dirs:
    - vendor/
    - internal/input/
  issues-exit-code: 0
  tests: true
  skip-files:
    - \.pb\.go$


output:
  format: colored-line-number

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - funlen
        - dupl
        - gosec
    - path: internal/input/
      linters:
        - gocyclo
        - funlen
        - godot
        - godox
        - dupl
        - gofmt
        - gci
        - gofumpt
        - goimports
        - gosimple

