linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - revive
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/obalunenko/advent-of-code
  revive:
    # see https://github.com/mgechev/revive#available-rules for details.
    ignore-generated-header: true
    severity: warning
    rules:
      - name: indent-error-flow
        severity: warning
      - name: exported
        severity: warning
      - name: defer
        severity: warning
        arguments: [ [ "call-chain", "loop", "method-call", "recover", "return" ] ]

run:
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor/
  skip-files:
    - \.pb\.go$
  out-format:
    - github-actions

issues:
  exclude-use-default: false
  exclude:
    # for "public interface + private struct implementation" cases only!
    - exported func * returns unexported type *, which can be annoying to use
    - should have a package comment, unless it's in another file for this package
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - funlen
        - dupl
        - gosec
    - path: internal/input/
      linters:
        - gocyclo
        - funlen
        - godot
        - godox
        - dupl
        - gofmt
        - gci
        - gofumpt
        - goimports
        - gosimple
