version: "2"
run:
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
    checkstyle:
      path: report.xml
  path-prefix: ""
linters:
  default: none
  enable:
    - errcheck
    - revive
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    revive:
      severity: warning
      rules:
        - name: indent-error-flow
          severity: warning
        - name: exported
          severity: warning
        - name: defer
          arguments:
            - - call-chain
              - loop
              - method-call
              - recover
              - return
          severity: warning
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - funlen
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - dupl
          - funlen
          - gocyclo
          - godot
          - godox
          - staticcheck
        path: internal/input/
      - linters:
          - revive
        path: internal/puzzles/constants.go
      - path: (.+)\.go$
        text: exported func * returns unexported type *, which can be annoying to use
      - path: (.+)\.go$
        text: should have a package comment, unless it's in another file for this package
    paths:
      - \.pb\.go$
      - vendor/
      - third_party$
      - builtin$
      - examples$
issues:
  uniq-by-line: true
  new: true
  fix: false
severity:
  default: error
  rules:
    - linters:
        - dupl
      severity: warning
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/obalunenko/advent-of-code
  exclusions:
    generated: lax
    paths:
      - \.pb\.go$
      - vendor/
      - third_party$
      - builtin$
      - examples$
      - internal/input/
