version: "2"
run:
  issues-exit-code: 0
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
    checkstyle:
      path: report.xml
  path-prefix: ""
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl
  settings:
    depguard:
      rules:
        main:
          list-mode: original
          files:
            - '!**/*_a _file.go'
          deny:
            - pkg: math/rand$
              desc: use math/rand/v2
            - pkg: github.com/sirupsen/logrus
              desc: not allowed - github.com/obalunenko/logger
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - hugeParam
        - octalLiteral
        - wrapperFunc
        - sloppyReassign
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    govet:
      disable:
        - fieldalignment
      enable-all: true
      settings:
        shadow:
          strict: false
    lll:
      line-length: 140
    misspell:
      locale: US
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
        - assign
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - funlen
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - dupl
          - funlen
          - gocyclo
          - godot
          - godox
          - staticcheck
        path: internal/input/
      - linters:
          - revive
        path: internal/puzzles/constants.go
      - linters:
          - gochecknoinits
        path: internal/puzzles/solutions/
      - path: (.+)\.go$
        text: exported func * returns unexported type *, which can be annoying to use
      - path: (.+)\.go$
        text: should have a package comment, unless it's in another file for this package
    paths:
      - \.pb\.go$
      - vendor/
      - third_party$
      - builtin$
      - examples$
issues:
  uniq-by-line: true
  new: true
  fix: false
severity:
  default: error
  rules:
    - linters:
        - dupl
      severity: warning
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/obalunenko)
        - localmodule
    goimports:
      local-prefixes:
        - github.com/obalunenko/advent-of-code
  exclusions:
    generated: lax
    paths:
      - \.pb\.go$
      - vendor/
      - third_party$
      - builtin$
      - examples$
      - internal/input/
