name: Go Build & Test
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Build & Test
    steps:
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      
      - name: Install tools
        run: |
          make install-tools
      
      - name: Vet
        run: |
          make vet
          
      - name: Lint
        run: |
          make lint-ci
          
      - name: Test
        run: |
          make test-cover
      
      - name: Cover report
        if: success()
        run: |
          bash <(curl -s https://codecov.io/bash)
          
      - name: Run GoReleaser snapshot
        if: success()
        run: |
          make release-local-snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOVERSION: $(go version | awk '{print $3;}')

