name: Update README ⭐
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Upate 2021 year
        uses: k2bd/advent-readme-stars@v1.0.1
        env:
          YEAR: 2021
        with:
          userId: ${{ secrets.AOC_USER_ID }}
          leaderboardId: ${{ secrets.AOC_BOARD_ID}}
          sessionCookie: ${{ secrets.AOC_SESSION }}
          readmeLocation: README.md
          headerPrefix: "###"
          year: $YEAR
          tableMarker: <!--- advent_readme_stars table [$YEAR] --->
          starSymbol: "⭐"

      - name: Upate 2020 year
        uses: k2bd/advent-readme-stars@v1.0.1
        env:
          YEAR: 2020
        with:
          userId: ${{ secrets.AOC_USER_ID }}
          leaderboardId: ${{ secrets.AOC_BOARD_ID}}
          sessionCookie: ${{ secrets.AOC_SESSION }}
          readmeLocation: README.md
          headerPrefix: "###"
          year: $YEAR
          tableMarker: <!--- advent_readme_stars table [$YEAR] --->
          starSymbol: "⭐"

      - name: Upate 2019 year
        uses: k2bd/advent-readme-stars@v1.0.1
        env:
          YEAR: 2019
        with:
          userId: ${{ secrets.AOC_USER_ID }}
          leaderboardId: ${{ secrets.AOC_BOARD_ID}}
          sessionCookie: ${{ secrets.AOC_SESSION }}
          readmeLocation: README.md
          headerPrefix: "###"
          year: $YEAR
          tableMarker: <!--- advent_readme_stars table [$YEAR] --->
          starSymbol: "⭐"

      - name: Upate 2018 year
        uses: k2bd/advent-readme-stars@v1.0.1
        env:
          YEAR: 2018
        with:
          userId: ${{ secrets.AOC_USER_ID }}
          leaderboardId: ${{ secrets.AOC_BOARD_ID}}
          sessionCookie: ${{ secrets.AOC_SESSION }}
          readmeLocation: README.md
          headerPrefix: "###"
          year: $YEAR
          tableMarker: <!--- advent_readme_stars table [$YEAR] --->
          starSymbol: "⭐"

      - name: Upate 2017 year
        uses: k2bd/advent-readme-stars@v1.0.1
        env:
          YEAR: 2017
        with:
          userId: ${{ secrets.AOC_USER_ID }}
          leaderboardId: ${{ secrets.AOC_BOARD_ID}}
          sessionCookie: ${{ secrets.AOC_SESSION }}
          readmeLocation: README.md
          headerPrefix: "###"
          year: $YEAR
          tableMarker: <!--- advent_readme_stars table [$YEAR] --->
          starSymbol: "⭐"

      - name: Upate 2016 year
        uses: k2bd/advent-readme-stars@v1.0.1
        env:
          YEAR: 2016
        with:
          userId: ${{ secrets.AOC_USER_ID }}
          leaderboardId: ${{ secrets.AOC_BOARD_ID}}
          sessionCookie: ${{ secrets.AOC_SESSION }}
          readmeLocation: README.md
          headerPrefix: "###"
          year: $YEAR
          tableMarker: <!--- advent_readme_stars table [$YEAR] --->
          starSymbol: "⭐"

      - name: Upate 2015 year
        uses: k2bd/advent-readme-stars@v1.0.1
        env:
          YEAR: 2015
        with:
          userId: ${{ secrets.AOC_USER_ID }}
          leaderboardId: ${{ secrets.AOC_BOARD_ID}}
          sessionCookie: ${{ secrets.AOC_SESSION }}
          readmeLocation: README.md
          headerPrefix: "###"
          year: $YEAR
          tableMarker: <!--- advent_readme_stars table [$YEAR] --->
          starSymbol: "⭐"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: Update README stars.
