name: Update README ⭐
on:
  push:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Upate 2015 year
        uses: k2bd/advent-readme-stars@v1.0.1
        with:
          userId: ${{ secrets.AOC_USER_ID }}
          sessionCookie: ${{ secrets.AOC_SESSION }}
          readmeLocation: README.md
          headerPrefix: "##"
          year: 2015
          tableMarker: <!--- advent_readme_stars table [2015] --->
          starSymbol: "⭐"

      - name: Upate 2016 year
        uses: k2bd/advent-readme-stars@v1.0.1
        with:
          userId: ${{ secrets.AOC_USER_ID }}
          sessionCookie: ${{ secrets.AOC_SESSION }}
          readmeLocation: README.md
          headerPrefix: "##"
          year: 2016
          tableMarker: <!--- advent_readme_stars table [2016] --->
          starSymbol: "⭐"

      - name: Upate 2017 year
        uses: k2bd/advent-readme-stars@v1.0.1
        with:
          userId: ${{ secrets.AOC_USER_ID }}
          sessionCookie: ${{ secrets.AOC_SESSION }}
          readmeLocation: README.md
          headerPrefix: "##"
          year: 2017
          tableMarker: <!--- advent_readme_stars table [2017] --->
          starSymbol: "⭐"

      - name: Upate 2018 year
        uses: k2bd/advent-readme-stars@v1.0.1
        with:
          userId: ${{ secrets.AOC_USER_ID }}
          sessionCookie: ${{ secrets.AOC_SESSION }}
          readmeLocation: README.md
          headerPrefix: "##"
          year: 2018
          tableMarker: <!--- advent_readme_stars table [2018] --->
          starSymbol: "⭐"

      - name: Upate 2019 year
        uses: k2bd/advent-readme-stars@v1.0.1
        with:
          userId: ${{ secrets.AOC_USER_ID }}
          sessionCookie: ${{ secrets.AOC_SESSION }}
          readmeLocation: README.md
          headerPrefix: "##"
          year: 2019
          tableMarker: <!--- advent_readme_stars table [2019] --->
          starSymbol: "⭐"

      - name: Upate 2020 year
        uses: k2bd/advent-readme-stars@v1.0.1
        with:
          userId: ${{ secrets.AOC_USER_ID }}
          sessionCookie: ${{ secrets.AOC_SESSION }}
          readmeLocation: README.md
          headerPrefix: "##"
          year: 2020
          tableMarker: <!--- advent_readme_stars table [2020] --->
          starSymbol: "⭐"

      - name: Upate 2021 year
        uses: k2bd/advent-readme-stars@v1.0.1
        with:
          userId: ${{ secrets.AOC_USER_ID }}
          sessionCookie: ${{ secrets.AOC_SESSION }}
          readmeLocation: README.md
          headerPrefix: "##"
          year: 2021
          tableMarker: <!--- advent_readme_stars table [2021] --->
          starSymbol: "⭐"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: Update README stars for ${{ matrix.year }} year.
