name: Update README ⭐
on:
  push:
    branches:
      - 'master'
    paths:
      - "!**"
      - "internal/puzzles/**"
      - ".github/workflows/readme-stars.yml"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-22.04
    env:
      USER_ID: ${{ secrets.AOC_USER_ID }}
      BOARD_ID: ${{ secrets.AOC_BOARD_ID}}
      SESSION: ${{ secrets.AOC_SESSION }}
      HEADER_PFX: "###"
      README: README.md
      STAR_SYMBOL: "⭐"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update 2023 year
        uses: k2bd/advent-readme-stars@v1.0.3
        env:
          YEAR: 2023
        with:
          userId: ${{env.USER_ID}}
          leaderboardId: ${{env.BOARD_ID}}
          sessionCookie: ${{env.SESSION}}
          readmeLocation: ${{env.README}}
          headerPrefix: ${{env.HEADER_PFX}}
          year: ${{env.YEAR}}
          tableMarker: <!--- advent_readme_stars table [${{env.YEAR}}] --->
          starSymbol: ${{env.STAR_SYMBOL}}

      - name: Update 2022 year
        uses: k2bd/advent-readme-stars@v1.0.3
        env:
          YEAR: 2022
        with:
          userId: ${{env.USER_ID}}
          leaderboardId: ${{env.BOARD_ID}}
          sessionCookie: ${{env.SESSION}}
          readmeLocation: ${{env.README}}
          headerPrefix: ${{env.HEADER_PFX}}
          year: ${{env.YEAR}}
          tableMarker: <!--- advent_readme_stars table [${{env.YEAR}}] --->
          starSymbol: ${{env.STAR_SYMBOL}}

      - name: Update 2021 year
        uses: k2bd/advent-readme-stars@v1.0.3
        env:
          YEAR: 2021
        with:
          userId: ${{env.USER_ID}}
          leaderboardId: ${{env.BOARD_ID}}
          sessionCookie: ${{env.SESSION}}
          readmeLocation: ${{env.README}}
          headerPrefix: ${{env.HEADER_PFX}}
          year: ${{env.YEAR}}
          tableMarker: <!--- advent_readme_stars table [${{env.YEAR}}] --->
          starSymbol: ${{env.STAR_SYMBOL}}

      - name: Update 2020 year
        uses: k2bd/advent-readme-stars@v1.0.3
        env:
          YEAR: 2020
        with:
          userId: ${{env.USER_ID}}
          leaderboardId: ${{env.BOARD_ID}}
          sessionCookie: ${{env.SESSION}}
          readmeLocation: ${{env.README}}
          headerPrefix: ${{env.HEADER_PFX}}
          year: ${{env.YEAR}}
          tableMarker: <!--- advent_readme_stars table [${{env.YEAR}}] --->
          starSymbol: ${{env.STAR_SYMBOL}}

      - name: Update 2019 year
        uses: k2bd/advent-readme-stars@v1.0.3
        env:
          YEAR: 2019
        with:
          userId: ${{env.USER_ID}}
          leaderboardId: ${{env.BOARD_ID}}
          sessionCookie: ${{env.SESSION}}
          readmeLocation: ${{env.README}}
          headerPrefix: ${{env.HEADER_PFX}}
          year: ${{env.YEAR}}
          tableMarker: <!--- advent_readme_stars table [${{env.YEAR}}] --->
          starSymbol: ${{env.STAR_SYMBOL}}

      - name: Update 2018 year
        uses: k2bd/advent-readme-stars@v1.0.3
        env:
          YEAR: 2018
        with:
          userId: ${{env.USER_ID}}
          leaderboardId: ${{env.BOARD_ID}}
          sessionCookie: ${{env.SESSION}}
          readmeLocation: ${{env.README}}
          headerPrefix: ${{env.HEADER_PFX}}
          year: ${{env.YEAR}}
          tableMarker: <!--- advent_readme_stars table [${{env.YEAR}}] --->
          starSymbol: ${{env.STAR_SYMBOL}}

      - name: Update 2017 year
        uses: k2bd/advent-readme-stars@v1.0.3
        env:
          YEAR: 2017
        with:
          userId: ${{env.USER_ID}}
          leaderboardId: ${{env.BOARD_ID}}
          sessionCookie: ${{env.SESSION}}
          readmeLocation: ${{env.README}}
          headerPrefix: ${{env.HEADER_PFX}}
          year: ${{env.YEAR}}
          tableMarker: <!--- advent_readme_stars table [${{env.YEAR}}] --->
          starSymbol: ${{env.STAR_SYMBOL}}

      - name: Update 2016 year
        uses: k2bd/advent-readme-stars@v1.0.3
        env:
          YEAR: 2016
        with:
          userId: ${{env.USER_ID}}
          leaderboardId: ${{env.BOARD_ID}}
          sessionCookie: ${{env.SESSION}}
          readmeLocation: ${{env.README}}
          headerPrefix: ${{env.HEADER_PFX}}
          year: ${{env.YEAR}}
          tableMarker: <!--- advent_readme_stars table [${{env.YEAR}}] --->
          starSymbol: ${{env.STAR_SYMBOL}}

      - name: Update 2015 year
        uses: k2bd/advent-readme-stars@v1.0.3
        env:
          YEAR: 2015
        with:
          userId: ${{env.USER_ID}}
          leaderboardId: ${{env.BOARD_ID}}
          sessionCookie: ${{env.SESSION}}
          readmeLocation: ${{env.README}}
          headerPrefix: ${{env.HEADER_PFX}}
          year: ${{env.YEAR}}
          tableMarker: <!--- advent_readme_stars table [${{env.YEAR}}] --->
          starSymbol: ${{env.STAR_SYMBOL}}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: Update README stars.
