name: build

on:
  push:
    tags:
      - 'v*'
    branches:
      - "!*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      -
        name: Cache Go modules
        uses: actions/cache@v2.1.4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      -
        name: Make Setup
        run: |
          make install-tools
      -
        name: Upload coverage
        uses: codecov/codecov-action@v1.2.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
      -
        name: Check
        run: |
          ./goreleaser check
      -
        name: GoReleaser
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            ./goreleaser
          elif [[ $GITHUB_REF == refs/heads/master ]]; then
            ./goreleaser --snapshot
          fi
      -
        name: Clear
        if: always() && startsWith(github.ref, 'refs/tags/v')
        run: |
          rm -f ${HOME}/.docker/config.json