name: Lint & Test & Build & Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - "!*"

jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ 'ubuntu-20.04' ]
        go: [ '1.17' ]
    runs-on: ${{ matrix.os }}
    name: Lint & Test & Build & Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Set up go
        uses: actions/setup-go@v2.1.4
        with:
          stable: 'true'
          go-version: ${{ matrix.go }}
      - run: |
          go version

      - name: Install tools
        run: |
          make install-tools

      - name: Vet
        run: |
          make vet

      - name: Lint
        run: |
          make lint-pipeline

      - name: Test
        run: |
          make test

      - name: Run GoReleaser
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make release
